config/routes.rb
Rails.application.routes.draw do

	root 'employees#index'

	get '/employees' => 'employees#index'
	post '/employees' => 'employees#create'
	get '/employees/new' => 'employees#new', as: 'new_employee'
	get '/employees/:id' => 'employees#show', as: 'employee'
	get '/employees/:id/edit' => 'employees#edit', as: 'edit_employee' 

	

  #get 'employees/index'
  #get 'employees/show'
  #get 'employees/new'
  #get 'employees/create'
  #get 'employees/edit'
  #get 'employees/update'
  #get 'employees/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :edit, :destroy]

  def index
    @employees = Employee.all.order("id ASC")
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    employee = Employee.new(employee_params)
    #@employee = Employee.create(employee_params)
    if employee.save
      redirect_to employee_path(employee.id)
    else
      redirect_to new_employee_path
    end
  end

  def edit
  end

  def update
    @employee = Employee.update(employee_params)
    if @employee.save
      flash[:success] = "Employee Successfully updated!"
      redirect_to @employee
    else
      flash[:error] = "Employee was not updated"
      render :edit
    end
  end

  def destroy 
    @employee.destroy
    redirect_to root_path
  end

  private

    def employee_params
      params.require(:employee).permit(:FirstName, :LastName, :Gender, :HiredDate, :Salary)
    end

    def find_employee
      @employee = Employee.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="container">
<form class="new_employee" id="new_employee" action="/employees" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="GJYt2u8kflg5ooRd2ACwV2URvAeXpWYPufZHpkdZUIFbkBUjlOub27noVpWgLyp0VXl974mJ2P6RzjvJr9heSQ==" />
  <div class="form-row">
    <div class="form-group col-md-6">
    <label for="employee_FirstName" class="col-sm-2 col-form-label">FirstName</label>
    <div class="col-sm-10">
      <input type="text" name="employee[FirstName]" id="employee_FirstName" class="form-control"/>
    </div>
  </div>
  <div class="form-group col-md-6">
    <label for="employee_LastName" class="col-sm-2 col-form-label">LastName</label>
    <div class="col-sm-10">
      <input type="text" name="employee[LastName]" id="employee_LastName" class="form-control"/>
    </div>
  </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
    <label for="employee_Gender" class="col-sm-2 col-form-label">Gender</label>
    <div class="col-sm-10">
      <input type="text" name="employee[Gender]" id="employee_Gender" class="form-control"/>
    </div>
  </div>
  <div class="form-group col-md-6">
    <label for="employee_HiredDate" class="col-sm-2 col-form-label">HiredDate</label>
    <div class="col-sm-10">
      <input type="text" name="employee[HiredDate]" id="employee_HiredDate" class="form-control"/>
    </div>
  </div>
  </div>
  <div class="form-row">
  <div class="form-group col-md-6">
    <label for="employee_Salary" class="col-sm-2 col-form-label">Salary</label>
    <div class="col-sm-10">
      <input type="text" name="employee[Salary]" id="employee_Salary" class="form-control"/>
    </div>
  </div>
  </div>
  <input type="submit" name="commit" value="Submit" data-disable-with="Add" class="btn btn-primary btn-lg btn-block"/>
</form>
</div>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<h1>Edit Employee Details</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<div class="container">
    <h1 style="text-align: center;">Employees</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Gender</th>
                <th scope="col">Hired Date</th>
                <th scope="col">Salary</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @employees.each do |employee|%>
            <tr>
                <th scope="row">
                    <%= employee.id %>
                </th>
                <td>
                    <%= employee.FirstName %>
                </td>
                <td>
                    <%= employee.LastName %>
                </td>
                <td>
                    <%= employee.Gender %>
                </td>
                <td>
                    <%= employee.HiredDate %>
                </td>
                <td>
                    <%= employee.Salary %>
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-light"><%= link_to "view", employee_path(employee.id) %></button>
                        <button type="button" class="btn btn-light"><%= link_to "Edit", edit_employee_path(employee.id) %></button>
                        <button type="button" class="btn btn-light"><%= link_to "Delete", employee_path(employee.id), method: :delete, data: { confirm: "Are You Sure"} %></button>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <button type="button" class="btn btn-light btn-lg btn-block"><%= link_to "Add Employee", new_employee_path %></button>
</div>

app/views/employees/new.html.erb
<h1>Add New Employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col">
                        <div class="profile-head p-5">
                                    <h2>
                                        <%= @employee.FirstName %> <%= @employee.LastName %>
                                    </h2>
                                    
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col">
                                                <label>Employee Id</label>
                                            </div>
                                            <div class="col">
                                                <p><%= @employee.id %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <label>First Name</label>
                                            </div>
                                            <div class="col">
                                                <p><%= @employee.FirstName %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <label>Last Name</label>
                                            </div>
                                            <div class="col">
                                                <p><%= @employee.LastName %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <label>Gender</label>
                                            </div>
                                            <div class="col">
                                                <p><%= @employee.Gender %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <label>HiredDate</label>
                                            </div>
                                            <div class="col">
                                                <p><%= @employee.HiredDate %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <label>Salary</label>
                                            </div>
                                            <div class="col">
                                                <p><%= @employee.Salary %></p>
                                            </div>
                                        </div>
                            </div>
                            <div class="row">
                            	<div class="col">
                        <button type="button" class="btn btn-light"><%= link_to "Edit", edit_employee_path(@employee) %></button>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
                            

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SAAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/employees">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>